blumilksoftware/website

src/locale/en.json

I'm helping

---

src/locale/en.json

Small grammar fixes. Thanks, Malwina!

#66 - grammar

---

robots.txt

#64 - added robots.txt

---

package-lock.json
public/sitemap.xml

I updated all @dependabot requests in one commit:
- #27 - Bump tailwindcss from 2.0.2 to 2.0.3
- #27 - Bump svelte-preprocess from 4.6.5 to 4.6.9
- #27 - Bump slugify from 1.4.6 to 1.4.7
- #27 - Bump svelte from 3.32.1 to 3.34.0
- #27 - Bump postcss from 8.2.4 to 8.2.6

#27 - dependencies batched update

---

public/index.html
src/components/meta-title.svelte
src/locale/en.json
src/locale/pl.json
src/pages/_fallback.svelte
src/pages/_layout.svelte
src/pages/about.svelte
src/pages/career.svelte
src/pages/company.svelte
src/pages/contact.svelte
src/pages/index.svelte
src/pages/privacy.svelte
src/pages/services.svelte

#62 - changing page title

---

index.html

#98 - added gsc meta tag

---

.eslintrc.js
.github/workflows/title.yml
rollup.config.js
src/components/map.svelte
src/pages/contact.svelte

I think the problem was with rendering env after bumping `dotenv` to 10 version.
@EwelinaLasowy we need to think how to automate these Cypress tests in CI to avoid situations like this in the future.

#104 - contact page bug fix

---

src/components/reference.svelte
src/components/ribbon.svelte
src/pages/career/index.svelte
src/pages/contact.svelte
src/sections/about/tools.svelte

#137 - bubbles z position

---

src/locale/en.json
src/locale/pl.json

#66 - proofreading

---

.github/workflows/deploy.yml

#171 - build directory changed

---

readme.md
src/locale/en.json
src/locale/pl.json
src/pages/contact.svelte

This should close #183.
Changes:
- better "Contact" page:
Before:
After:
- better descriptions on "Partnership" page
Overall, I didn't change a lot of texts, because they are okay.

#183 - UX writing

---

src/assets/contact.js
src/locale/en.json
src/locale/pl.json
src/pages/company.svelte

Added company phone and e-mail on company info page.
Preview:
Before merge we must update data for real data.

#194 - company phone and e-mail

---

app/Filament/Resources/UserResource.php
app/Filament/Resources/UserResource/Pages/CreateUser.php
app/Filament/Resources/UserResource/Pages/EditUser.php
app/Filament/Resources/UserResource/Pages/ListUsers.php
app/Providers/Filament/AdminPanelProvider.php
bootstrap/providers.php
composer.json
composer.lock
environment/dev/app/Dockerfile

Added [Filament](https://filamentphp.com/) for administration purpose, for creating CRUD's to managing resources on our website.

- filament initialization

---

.dockerignore
.github/workflows/deploy-to-beta.yml
Makefile
bootstrap/app.php
config/services.php
environment/prod/app/Dockerfile
environment/prod/deployment/beta/Makefile
environment/prod/deployment/beta/docker-compose.beta.yml
environment/prod/deployment/scripts/post-deploy-actions.sh
resources/views/contact.blade.php

This PR fixes deployment process and related stuff.

#264 - fix beta deployment

---

database/seeders/BetaSeeder.php
database/seeders/LocalEnvironmentSeeder.php
database/seeders/UsersSeeder.php

In this pr I added BetaSeeder - just seeded two users - admin and moderator. On beta we don't want to seed data like on local.

- add beta seeder

---

database/seeders/UsersSeeder.php

I hope for now seeder on beta will work

- fix seeder on beta

---

app/Filament/Resources/ActivityResource.php
package-lock.json
package.json
resources/views/activity.blade.php
tailwind.config.js

Editing panel:
Displaying description:
It should close #270.

#270 - add WYSIWYG editor to activity description 

---

app/Filament/Resources/CaseStudyResource.php

Little fix in CaseStudyResource.php, set unique record.

- fix CaseStudyResource.php

---

app/Filament/Resources/ContactFormResource.php
app/Http/Controllers/ContactController.php
app/Http/Requests/StoreRequest.php
app/Models/ContactForm.php
database/factories/ContactFormFactory.php
database/migrations/2024_06_27_135034_add_topic_to_contact_forms_table.php
lang/en/toast.php
lang/pl/toast.php
lang/pl/validation.php
resources/views/components/toast.blade.php
resources/views/contact.blade.php
resources/views/layout/public.blade.php
routes/web.php

Added possibility to send form with proper validation, also created component for toast.
Toast: 
Validation:
It should close #261

#261 - add message handling to contact page

---

app/Http/Controllers/CompanyDataController.php
lang/en/content.php
lang/en/footer.php
lang/en/meta.php
lang/pl/content.php
lang/pl/footer.php
lang/pl/meta.php
lang/pl/routes.php
resources/views/company-data.blade.php
resources/views/components/icons/mail.blade.php
resources/views/components/icons/phone.blade.php
resources/views/layout/footer.blade.php
resources/views/layout/public.blade.php
routes/web.php

I've done company data page and changed a bit footer to apply changes discussed yesterday.
It should close #319.
[Desktop design](https://www.figma.com/design/sdPYb47iLBwsA2FQMIu5BR/Blumilk?node-id=773-5126&t=akuYglgnotreuEOV-0)
[Mobile design](https://www.figma.com/design/2QnCtqnBUqCoBnoys47J9d/MOBILE?node-id=63-1586&t=UnrjPKJvBpLNZTrZ-0)

#319 - company data page

---

app/Filament/Resources/ProjectResource.php

This pr fixes bug with displaying projects.

- fix project templates display

---

resources/views/layout/public.blade.php
resources/views/single-news.blade.php

Updated placement of facebook meta tags.
It should close #296

#296 - seo meta tags

---

app/Filament/Resources/NewsResource.php

#354 - automatically slug for title

---

resources/views/components/news-card.blade.php
resources/views/single-news.blade.php

#356 - change image style in news

---

environment/prod/deployment/scripts/post-deploy-actions.sh

This PR implements to post-deploy-actions a new `php artisan filament:optimize` command which aims to optimize Filament in beta. 
The Laravel commands `php artisan _:cache` will also be changed to `php artisan optimize`.
This should close #360

#360 - beta improvement

---

lang/en/content.php
lang/pl/content.php
resources/views/home.blade.php

- change tiles order

---

app/Http/Controllers/NewsController.php
database/seeders/LocalEnvironmentSeeder.php
lang/en/content.php
lang/pl/content.php
resources/views/about.blade.php
resources/views/components/small-primary-button.blade.php
resources/views/home.blade.php
resources/views/news.blade.php
resources/views/single-news.blade.php

Due to Kasia request, I change apartment number -> from 5F/5 to 5F/3
Also I fixed things requested by Kasia:
- change color of button "Zobacz więcej projektów"
- change top padding on "O firmie" page
- change title to be in one line on homepage
And with a big help @Baakoma we fixed #367.

#367 - change apartment number

---

lang/en/content.php
lang/pl/content.php
resources/views/components/small-primary-button.blade.php

In this pr:
- centered text in CTA buttons
- changed one title an home page

- center text button

---

.github/workflows/deploy-to-prod.yml

init for test deploy to production #369

#368 - deploy to prod init

---

lang/en/content.php
lang/en/footer.php
lang/pl/content.php
lang/pl/footer.php
resources/views/contact.blade.php
resources/views/layout/footer.blade.php

In this PR I changed two little things:
1. Added country to address in contact page (plus changed PascalCase to snake_case in one translation key):
2. Added source code link in footer and adjusted padding:

- contact page and footer tweaks

---

app/Filament/Resources/ReferenceResource.php
app/Models/Reference.php
resources/views/projects/carbon.blade.php

In this pr:
- added position in English
- added section "Text us!" in carbon projekt - thanks @AleksandraKozubal for letting me know

- add position in English

---

environment/prod/deployment/prod/docker-compose.prod.yml

This PR adds permanent redirect (301) from www to non-www on prod env.

- redirect www to non-www on prod

---

app/Console/Commands/ConvertToWebp.php
app/Filament/Resources/NewsResource.php
app/Filament/Resources/ProjectResource.php
app/Filament/Resources/ReferenceResource.php
app/Helpers/ImageConverter.php
app/Models/Project.php
composer.json
composer.lock
environment/dev/app/Dockerfile
environment/prod/app/Dockerfile

It should close #383 
It converts images from any accepted mime type to webp. Additionaly I created command to convert existing images to webp.

#383 - webp conversion

---

.env.example
docker-compose.yml
vite.config.js

This pull request includes several changes to configuration files for the website development environment. The changes primarily focus on updating environment variables, modifying Docker Compose configurations, and adjusting Vite server settings.
* [`.env.example`](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cL6-R10): Updated `APP_URL` to use HTTPS and added new Docker host names for the application, Mailpit, and Vite development server.
* `docker-compose.yml`: 
* Renamed the network `traefik-proxy-blumilk-local` to `traefik-proxy-blumilk-local-environment`. [[1]](diffhunk://#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L4-R4) [[2]](diffhunk://#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L41-R53) …

- adjust new blumilk environment
