.github/dependabot.yml, package-lock.json
I upgraded:
* @rollup/plugin-commonjs
* @rollup/plugin-node-resolve
* @rollup/plugin-replace
* @roxi/routify
* @tailwindcss/forms
* autoprefixer
* chai
* eslint
* eslint-plugin-mocha
* mocha
* postcss
* rollup
* slugify
* svelte
* svelte-i18n
* svelte-preprocess
* tailwindcss
+ I changed Dependabot to crate only one PR per month until they figure out how to work with batched PRs.
=> #27 - bumping dependencies versions

.github/workflows/check.yml, .github/workflows/deploy.yml, .github/workflows/title.yml
To unify all our repositories, I renamed `master` branch to `main`. It should close #147.
Btw, to all other developers:
>  The default branch has been renamed! `master` is now named `main`
> If you have a local clone, you can update it by running the following commands.
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> #147 - master to main

src/components/lead-section.svelte, src/layout/footer.svelte, src/pages/career/index.svelte, src/pages/company.svelte, src/pages/contact.svelte, src/pages/index.svelte, src/pages/partnerships.svelte, src/pages/privacy.svelte, src/pages/services.svelte, src/sections/about/photos.svelte, src/sections/about/references.svelte, src/sections/gdpr.svelte
This should close #159.
- changed illustrations padding for smaller resolutions
Before:
After:
- redesigned references section for mobiles
Before:
After:
- reduced headers text-size on home page (only for mobiles), because it looks bad on smaller resolutions
Before:
After:
- fixed footer, because on medium resolutions looks unattractive
Before:
After:
=> #159 - change illustrations padding for smaller resolutions

src/pages/career/developer.svelte, src/pages/career/index.svelte, src/pages/career/intern.svelte, src/pages/contact.svelte, src/pages/index.svelte, src/pages/privacy.svelte, src/pages/services.svelte
So, my previous pr #161 broke paddings for bigger resolutions and this pr fixes this.
Before (broken):
After (fixed):
=> #159 - fix image padding for bigger resolutions

.github/workflows/deploy.yml
Looks like I need to be more consistent with documentation about vresion numbers of GHA actions.
=> #171 - GHA deploy fixes

package.json
Looks like we had missing Routify build for building process in deploy. I hope this is the last PR about Vite migration.
Should close #171.
=> #171 - routify for build

app/Filament/Resources/ActivityResource.php, database/migrations/2024_06_28_074839_change_slug_in_activities_table.php, database/migrations/2024_06_28_081839_change_slug_in_case_studies_table.php
User can no longer create two activities with the same slug - fixed with migration and with activity resource rule.
Also added unique() to slug column in case study.
It should close #278.
=> #278 - fix slug in activities table

environment/prod/app/Dockerfile
This PR fixes composer install command during deployment. 
Plugins were ignored, but `laravel-localized-routes` package use plugin to autoload helpers.php file.
https://github.com/codezero-be/laravel-localized-routes/blob/master/composer.json#L65-L67
Sum up:
- composer install in the final stage is not running under root user
- plugins are enabled during composer install commands
---
related issues:
- #287 
Closes #287
=> - fix composer plugins

resources/views/company-data.blade.php
Fix icons on company data page.
=> - update icons

environment/prod/deployment/beta/docker-compose.beta.yml
This PR adds a volume in docker-compose.beta.yml so that after each re-deploy the added images are preserved, e.g. in added news.
This should close #344
=> #344 - add volume for storage

resources/views/single-news.blade.php
In this pr I fixed showing html tags in recommended news. Thanks @vojcc for reporting this
=> - fix to showing html tag to news

app/Providers/AppServiceProvider.php
This PR fixes missing `Accept-Language` header.
By default `$request->header()` returns `null` but `str_starts_with()` require `string` type.
Sentry issue:
- https://blumilk.sentry.io/issues/5994456914/?project=4508086290612224&referrer=project-issue-stream
```
TypeError
str_starts_with(): Argument #1 ($haystack) must be of type string, null given
```
=> - fix missing Accept-Language header

environment/prod/deployment/prod/docker-compose.prod.yml
From now Traefik will handle www.blumilk.pl subdomain correct.
=> - add www subdomain on prod

app/Http/Controllers/NewsController.php
This PR fixes `QueryException` errors caused by invalid UTF-8 byte sequences in tag search queries. It ensures that only valid UTF-8 strings are processed, preventing invalid byte sequences from causing database errors.
=> - fix UTF-8 encoding issue in tag query

app/DTOs/ContactFormResponse.php, app/Filament/Resources/ContactFormResource/Actions/RespondToContactFormMessageAction.php, app/Http/Requests/StoreRequest.php, app/Mail/ContactFormResponded.php, app/Models/ContactForm.php, database/migrations/2024_10_16_083511_add_lang_column_in_contact_forms_table.php, docker-compose.yml, lang/en/email.php, lang/pl/email.php, resources/views/email.blade.php
The changes made improve the user experience by allowing users to receive responses in their preferred language (more specifically, the language the site was in when they sent a message via the contact form).
=> - add English email template from contact form

resources/views/company-data.blade.php, resources/views/contact.blade.php
This PR:
- adds links to email and phone on company details page
- changes the way the IDs are clickable; right now when I doubleclick on VAT number, both label and number are selected; right now only number is selected
=> - company details page tweaks

app/Http/Requests/StoreRequest.php
This PR fixes `PDOException` errors caused by invalid UTF-8 byte sequences in contact form. It ensures that only valid UTF-8 strings are processed, preventing invalid byte sequences from causing database errors.
This should close #399.
=> #399 - fix encoding in contact form

resources/views/email.blade.php, resources/views/layout/footer.blade.php
In this pull request I fixed static date in footers (website, mail):
Now the date in the footer is updated automatically.
=> - fix date in footer

package-lock.json, package.json
After fresh clone and setup project, after running command `make run` I had error 
```
error when starting dev server:
TypeError: Invalid URL
at new URL (node:internal/url:816:29)
at getAdditionalAllowedHosts (file:///application/node_modules/vite/dist/node/chunks/dep-CjorC8P2.js:59194:29)
at resolveConfig (file:///application/node_modules/vite/dist/node/chunks/dep-CjorC8P2.js:66549:29)
at async _createServer (file:///application/node_modules/vite/dist/node/chunks/dep-CjorC8P2.js:62901:18)
at async CAC.<anonymous> (file:///application/node_modules/vite/dist/node/cli.js:736:20)
```
I read on the Internet that problem is with vite version - so I upgrade it and now it works like a charm
=> - fix invalid URL error

resources/views/layout/public.blade.php
Added meta tag in `head` section for site verification in `Google Search Console` which is need for Google Play account verification.
=> - google search console verification tag

resources/views/career.blade.php, resources/views/contact.blade.php, resources/views/layout/footer.blade.php, resources/views/layout/public.blade.php
This pull request includes updates to the `career` and `footer` views to add tracking for outbound link clicks and the inclusion of an analytics script in the public layout. The most important changes are listed below:
* [`resources/views/career.blade.php`](diffhunk://#diff-8829ca586302baad6ee5ec998e3169b245f9dd05823a6df78c39f25f0eb9361aL138-R140): Added `data-umami-event` and `data-umami-event-url` attributes to the "Apply Internship" button to track outbound link clicks.
* [`resources/views/layout/footer.blade.php`](diffhunk://#diff-178cb44ccf72f6f34cccea8a692d4160cfb745d3495f88fccc59a590b139ae32L7-R23): Added `data-umami-event` and `data-umami-event-url` attributes to all outbound links in the footer to track clicks. [[1]](diffhunk://#diff-178cb44ccf72f6f34cccea8a692d4160cfb745d3495f88f …
=> #20 - add umami analytics

app/Providers/AppServiceProvider.php, tests/Unit/RecaptchaTest.php
On Monday, an error occurred in production:
Server error: POST https://www.google.com/recaptcha/api/siteverify resulted in a 502 Bad Gateway response: ...
To improve error handling, this PR introduces a custom validator for reCAPTCHA.
=> - make custom validator for recaptcha
